//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int ID { get; set; }
        public int FilmID { get; set; }
        public int SalonID { get; set; }
        public int SeansID { get; set; }
        public int CalisanID { get; set; }
        public int MusteriID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string KoltukNo { get; set; }
        public decimal Fiyat { get; set; }
    
        public virtual Calisan Calisan { get; set; }
        public virtual Film Film { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Salon Salon { get; set; }
        public virtual Seans Seans { get; set; }
    }
}
